#!/bin/bash

echo "🎨 DOI Tool アイコン問題解決ガイド"
echo "=================================="

BASE_DIR="/Users/shigenoburyuto/Documents/GitHub/DOI_tool_ver1"

# 実行権限設定
chmod +x "$BASE_DIR/fix_icon.sh"
chmod +x "$BASE_DIR/force_apply_icon.sh"

echo ""
echo "🔍 現在の問題: アイコンがアプリに反映されていない"
echo ""
echo "💡 解決方法（順番に試してください）:"
echo ""
echo "方法1: 標準的なアイコン修正"
echo "   $BASE_DIR/fix_icon.sh"
echo ""
echo "方法2: 強制的なアイコン適用（推奨）"
echo "   $BASE_DIR/force_apply_icon.sh"
echo ""
echo "方法3: 手動での確認・修正"
echo "   • Finderでアプリを右クリック → 「情報を見る」"
echo "   • アイコンに画像をドラッグ&ドロップ"
echo ""
echo "🎯 まず方法2（強制適用）を試すことをお勧めします:"
echo ""
echo "実行コマンド:"
echo "   cd $BASE_DIR"
echo "   ./force_apply_icon.sh"
echo ""
echo "⚠️  注意: スクリプト実行時にsudo権限を求められる場合があります"
echo "（システムキャッシュクリアのため）"
echo ""
echo "🔄 実行後の確認:"
echo "   1. 30秒ほど待つ"
echo "   2. Finderでアプリを表示"
echo "   3. アイコンが美しいグラデーションデザインに変わっているか確認"
echo ""
